
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-15T13:29:45-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ade162b1d31f989548bf7c4c647694e02f0b4ef0",
 "version": "1.0.0b7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
