
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-29T07:55:20-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "8fc238e296af7d352227de341999a04e0dd200c1",
 "version": "1.0.0b4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
